############# English navigation ##############

# main menu
[[main]]
name = "Accueil"
pageRef = "/"
weight = 1

[[main]]
name = "Philosophie"
pageRef = "/philosophy"
weight = 2

[[main]]
name = "Formules"
pageRef = "/prices"
weight = 3

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 4

# footer menu
#[[footer]]
#name = "About"
#pageRef = "/about"
#weight = 1
#
#[[footer]]
#name = "Privacy Policy"
#pageRef = "/privacy-policy"
#weight = 3
